module.exports = {
    serverMapping: {
        follow: {},
        like_page: {},
        reactions: {},
        vip_like: {},
        vip_like_group: {},
        vip_view_video: {},
        comment: {},
        share: {},
        s_like: {},
        s_like_comment: {},
        buff_group: {},
        fb_event: {},


        follow_instagram: {},
        like_instagram: {},
        view_instagram: {},
        live_instagram: {},
        comment_instagram: {},
        video: {},
        vip_cmt: {},
        vip_live: {},
        view_story: {},
        view_other: {},
        view_60k_offline: {},
        view_60k_live: {},
        fb_view_100k_reel: {},
        view_tiktok: {},
        like_tiktok: {},
        like_comment_tiktok: {},
        follow_tiktok: {},
        comment_tiktok: {},
        live_tiktok: {},
        share_live_tiktok: {},
        like_live_tiktok: {},
        comment_live_tiktok: {},
        share_tiktok: {},
        vip_love_tiktok: {},
        vip_view_tiktok: {},
        favorite_tiktok: {},
        pk_tiktok: {},

        sub_lazada: {},

        member_telegram: {},
        view_telegram: {},
        reaction_telegram: {},
        review: {},
        checkin: {},
        like_youtube: {},
        like_youtube_short: {},
        view_youtube: {},
        view_youtube_short: {},
        view_youtube_4k: {},
        comment_youtube: {

        },
        sub_youtube: {},
        like_comment_youtube: {},
        tick_youtube: {},
        live_youtube: {},


        vip_share: {},
        vip_like_instagram: {},
        vip_comment_instagram: {},

        like_threads: {},
        follow_threads: {},

        sharegroup: {},
        livestream_v2: {},
        like_twitter: {},
        follow_twitter: {},
        view_twitter: {},
        retweet_twitter: {},
        comment_twitter: {},
        live_twitter: {},

        vip_like_twitter: {},
        vip_view_twitter: {},

        follow_shopee: {},
        love_shopee: {},
        like_review_shopee: {},
        live_shopee: {},

        google_map: {},
        rip_google_map: {},
        google_map_review: {},
    },
}